version: '3'
services:
  nginx:
    container_name: docker-nginx
    image: nginx:1.17.1-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
    container_name: docker-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    container_name: docker-app
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.gradle:/root/.gradle
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql
    command: gradle -Dspring.profiles.active=docker bootrun
