server:
  port: 8080

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
