FROM gradle:5.5.1-jdk8 AS build

#COPY --chown=gradle:gradle src /home/gradle/src
#WORKDIR /home/gradle/src
#RUN gradle build
#
#FROM openjdk:8-jdk-alpine
#EXPOSE 8080
#COPY --from=build /home/gradle/* /app/
#WORKDIR /app
#CMD gradle bootrun